schemaVersion: v1
runner:
  type: GITHUB_ACTION
materials:
  - type: ARTIFACT
    name: cli-linux-amd64
    output: true
  - type: ARTIFACT
    name: control-plane-linux-amd64
    output: true
  - type: ARTIFACT
    name: artifact-cas-linux-amd64
    output: true
  - type: ARTIFACT
    name: chainloop-plugin-discord-webhook-linux-amd64
    output: false
  - type: CONTAINER_IMAGE
    name: control-plane-image
    output: true
  - type: CONTAINER_IMAGE
    name: artifact-cas-image
    output: true
  - type: SBOM_CYCLONEDX_JSON
    name: sbom-control-plane
    output: false
    annotations:
      - name: component
        value: control-plane
  - type: SBOM_CYCLONEDX_JSON
    name: sbom-artifact-cas
    output: false
    annotations:
      - name: component
        value: cas
  - type: ARTIFACT
    name: cli-linux-arm64
    output: true
  - type: ARTIFACT
    name: chainloop-plugin-smtp-linux-amd64
    output: false
  - type: ARTIFACT
    name: chainloop-plugin-dependency-track-linux-amd64
    output: false