# Contract for helm-package workflow
apiVersion: chainloop.dev/v1
kind: Contract
metadata:
  name: chainloop-vault-helm-package
  description: Contract for Vault Helm package workflow
spec:
  runner:
    type: GITHUB_ACTION
  materials:
    - type: HELM_CHART
      name: helm-chart
      output: true
    - type: CONTAINER_IMAGE
      name: control-plane-image
      output: true
    - type: CONTAINER_IMAGE
      name: artifact-cas-image
      output: true
  policies:
    attestation:
      - ref: source-commit
        with:
          check_signature: yes
          check_author_verified: yes
    materials:
      - ref: artifact-signed
  policyGroups:
    - ref: slsa-checks
      with:
        runner: GITHUB_ACTION