schemaVersion: v1
policies:
  materials:
    - ref: sbom-licenses
    - ref: sbom-freshness
    - ref: sbom-banned-licenses
      with:
        licenses: AGPL-1.0-only, AGPL-1.0-or-later, AGPL-3.0-only, AGPL-3.0-or-later
    - ref: sbom-banned-components
      with:
        components: log4j@2.14.1
  attestation:
    - ref: sbom-present
    - ref: source-commit