schemaVersion: v1
runner:
  type: GITHUB_ACTION
materials:
  - type: ARTIFACT
    name: built-site
    optional: false
    output: true
  - type: SBOM_CYCLONEDX_JSON
    name: sbom-cdx
    output: false
  - type: SBOM_SPDX_JSON
    name: sbom-spdx
    output: false
policies:
  attestation:
    - ref: source-commit
  materials:
    - ref: sbom-present