# contract used in release workflow
apiVersion: chainloop.dev/v1
kind: Contract
metadata:
  name: chainloop-chainloop-github-release
  description: Contract for Chainloop GitHub release workflow
spec:
  policies:
    attestation:
      - ref: source-commit
        with:
          check_signature: yes
  policyGroups:
    - ref: slsa-checks
      with:
        runner: GITHUB_ACTION
    - ref: vulnerability-management
      with:
        severity: "HIGH"
