{{- /*
Copyright Chainloop, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.controlplane.timestampAuthorities }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chainloop.controlplane.fullname" . }}-tsa
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "chainloop.controlplane.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- range $index, $tsa := .Values.controlplane.timestampAuthorities }}
  chain-{{$index}}.pem: |
    {{ $.Files.Get $tsa.certChainFile | nindent 4 }}
  {{- end }}
{{- end }}