name: Close inactive issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@3a9db7e6a41a89f618792c92c0e97cc736e1b13f # v10.0.0
        with:
          days-before-issue-stale: 90
          days-before-issue-close: 14
          stale-issue-label: stale
          stale-issue-message: >
            This issue is stale because it has been open for 90 days with no activity.
            It will be closed in 14 days if no further activity occurs.
          close-issue-message: >
            This issue was closed because it has been inactive for 14 days since being marked as stale.
            Feel free to reopen if it is still relevant.
          days-before-pr-stale: 90
          days-before-pr-close: 14
          stale-pr-label: stale
          stale-pr-message: >
            This pull request is stale because it has been open for 90 days with no activity.
            It will be closed in 14 days if no further activity occurs.
          close-pr-message: >
            This pull request was closed because it has been inactive for 14 days since being marked as stale.
            Feel free to reopen if it is still relevant.
          exempt-issue-labels: pinned,security
          exempt-pr-labels: pinned,security
